#ifndef OPENMITTSU_PROTOCOL_CONTACTIDSTATUS_H_
#define OPENMITTSU_PROTOCOL_CONTACTIDSTATUS_H_

enum class ContactIdStatus {
	STATUS_INVALID,
	STATUS_INACTIVE,
	STATUS_ACTIVE
};

#endif // OPENMITTSU_PROTOCOL_CONTACTIDSTATUS_H_
