#ifndef OPENMITTSU_EXCEPTIONS_ILLEGALFUNCTIONCALLEXCEPTION_H_
#define OPENMITTSU_EXCEPTIONS_ILLEGALFUNCTIONCALLEXCEPTION_H_

#include "src/exceptions/BaseException.h"
#include "src/exceptions/ExceptionMacros.h"

OPENMITTSU_NEW_EXCEPTION(IllegalFunctionCallException)

#endif /* OPENMITTSU_EXCEPTIONS_ILLEGALFUNCTIONCALLEXCEPTION_H_ */
