#ifndef OPENMITTSU_EXCEPTIONS_ILLEGALARGUMENTEXCEPTION_H_
#define OPENMITTSU_EXCEPTIONS_ILLEGALARGUMENTEXCEPTION_H_

#include "exceptions/BaseException.h"
#include "exceptions/ExceptionMacros.h"

OPENMITTSU_NEW_EXCEPTION(IllegalArgumentException)

#endif /* OPENMITTSU_EXCEPTIONS_ILLEGALARGUMENTEXCEPTION_H_ */
