#ifndef OPENMITTSU_EXCEPTIONS_INVALIDPASSWORDORDATABASEEXCEPTION_H_
#define OPENMITTSU_EXCEPTIONS_INVALIDPASSWORDORDATABASEEXCEPTION_H_

#include "src/exceptions/BaseException.h"
#include "src/exceptions/ExceptionMacros.h"

OPENMITTSU_NEW_EXCEPTION(InvalidPasswordOrDatabaseException)
 
#endif /* OPENMITTSU_EXCEPTIONS_INVALIDPASSWORDORDATABASEEXCEPTION_H_ */
